# Generated by Django 4.2.28 on 2026-02-16 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'core_brand',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'db_table': 'core_component',
            },
        ),
        migrations.CreateModel(
            name='ProtectionZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'core_protectionzone',
            },
        ),
        migrations.CreateModel(
            name='TechModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.brand')),
            ],
            options={
                'db_table': 'core_model',
            },
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('search_keywords', models.TextField(blank=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.techmodel')),
            ],
            options={
                'db_table': 'core_modification',
            },
        ),
        migrations.CreateModel(
            name='AssemblyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.component')),
                ('modification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modification')),
                ('protection_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.protectionzone')),
            ],
            options={
                'db_table': 'core_assemblytemplate',
            },
        ),
        migrations.AddConstraint(
            model_name='techmodel',
            constraint=models.UniqueConstraint(fields=('brand', 'name'), name='core_techmodel_brand_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='modification',
            constraint=models.UniqueConstraint(fields=('model', 'name'), name='core_modification_model_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='assemblytemplate',
            constraint=models.UniqueConstraint(fields=('modification', 'protection_zone', 'component'), name='core_assemblytemplate_mod_zone_comp_uniq'),
        ),
    ]
